### ISSUE TITLE
The window size has issues

### ISSUE THREAD

**Issue by Dznan** [MichaelisTrofficus/hampel_filter#4]
https://github.com/MichaelisTrofficus/hampel_filter/blob/f8970569c847aeac6f24124116bfee9af09d5d3f/src/hampel.py#L48

The window size should be `2*window_size + 1`

**Comment by libonancaesar** [comment]
totally agreed. 

> https://github.com/MichaelisTrofficus/hampel_filter/blob/f8970569c847aeac6f24124116bfee9af09d5d3f/src/hampel.py#L48
> 
> The window size should be `2*window_size + 1`

Found this problem too.

**Comment by MichaelisTrofficus** [comment]
Hi, sorry for the delay, last year was kind of crazy for me and I didn't find any time to work on this library hahha. 

If you look at the code now you'll see some major changes (version 1.0.1), since hampel is no longer implemented using pandas, but with Cython. From my experiments I estimate a speed improvement of x6 approximately, so it made sense to make this change.  Using this new version, **the issue  you are mentioning is also solved**. For example:

```python
from hampel import hampel

data = np.array([2., 25. 6.])
outlier_indices = hampel(data, window_size=3).outlier_indices
```
If you print the `outlier_indices` now, it should be `[1]`.

 Please let me know if everything works correctly now and, VERY IMPORTANT, take a look at the updated README.md because there are some changes you must do in your code from now on (if you want to use version 1.0.1 and above).

 Thanks!
